lexer:
- lib/lexer/*

coretypes:
- lib/core_types/*

parser:
- lib/parser/*

runtime:
- lib/runtime/*

utils:
- lib/utils/*

AST:
- lib/utils/*
- lib/utils/AST.dart

tests:
- test/*

examples:
- examples/*

core:
- core/*
