lexer:
- lib/lexer/**

coretypes:
- lib/core_types/**

parser:
- lib/parser/**

runtime:
- lib/runtime/**

utils:
- lib/utils/**

AST:
- lib/utils/ast/**

tests:
- test/**

examples:
- examples/**

core:
- core/**


docs:
- docs/**
