# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Deploy

on:
  push:
    branches: [ master ]
    paths:
      - docs/**

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: scripts
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn Install
        run: yarn install
      - name: Yarn Build
        run: yarn build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Firebase deploy
        run: firebase deploy --token ${{secrets.FIREBASE_TOKEN}} --project birbolang
